# **Array Creation**

In [ ]:
import numpy as np

In [ ]:
arr_list=np.array([1,2,4,3])
print(arr_list)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 4 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
#ALL ARRAY ELEMENT ARE ZERO SYNTAX:- arr_name=np.zeros((row,col))
arr_zeros=np.zeros((3,4))
print(arr_zeros)

#ALL ARRAY ELEMENT ARE ONE SYNTAX:- arr_name=np.zeros((row,col))
arr_ones=np.ones((3,4))
print(arr_ones)

#ALL ARRAY ELEMENT ARE SPECIFIED  VALUE SYNTAX:- arr_name=np.full((row,col),value)
arr_full=np.full((3,4),7)
print(arr_full)

#FOR UNINITIALIZED VALUE SYNTAX:
arr_empty=np.empty((2,2))
print(arr_empty)

#LIKE EXISTING ARRAYS
arr_like=np.zeros_like(arr_list) #same shape and data type lik arr_list array for element 0
print(arr_like)

arr_like=np.ones_like(arr_list) #same shape and data type lik arr_list array for element 1
print(arr_like)

arr_like=np.full_like(arr_list,5) #same shape and data type lik arr_list array for element 5
print(arr_like)

arr_like=np.empty_like(arr_list) #same shape and data type lik arr_list array for empty
print(arr_like)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[5.e-324 5.e-324]
 [5.e-324 5.e-324]]
[0 0 0 0]
[1 1 1 1]
[5 5 5 5]
[1 1 1 1]


In [69]:
#FOR SEQUENCE SYNTAX :- arr-name=np.arrange(start,end,defference)
range_arr=np.arange(10,30,2)
print(range_arr)

#LIN SPACE SYNTAX :- arr_name=np.linspace(start,stop,expected num of element)
lin_arr=np.linspace(10,30,5)
print(lin_arr)

#LOG SPACE SYNTAX :-arr_name=np.logspace(start,stop,expexted num of element)
log_arr=np.logspace(0,2,3)
print(log_arr)

#IDENTITY MATRIX SYNTAX:-arr_name=np.identity(row or col)
eye_mat=np.eye(3)
print(eye_mat)
print("-----------------")
id_mat=np.identity(3)
print(id_mat)

#DIAGONAL MATRIX SYNTAX:-arr_name=np.diag(DIAGONAL ELEMNENT)
diag_mat=np.diag([1,2,3,4])
print(diag_mat)

#EXTRACT DIAGONAL ELEMENT FROM DIAGONAL MATRIX SYNTAX:- arr_name=np.diag(DIAGONAL ARRAY NAME)
ext_arr=np.diag(diag_mat)
print(ext_arr)

#RANDOM NUMBERS SYNTAX: np.random.seed(arguments)
                        #arr_name=np.random.rand(row,col)
np.random.seed(42)
rand_arr  =np.random.rand(2,3)
print(rand_arr)
print("----------------------------------")
#STANDARD NORMAL DISTRIBUTION :arr_name=np.random.randn(row, col)
norm_arr=np.random.randn(2,3)
print(norm_arr)
print("----------------------------------")
#RANDOM INTEGERS SYTAX :- arr_name=np.random.randint(low,high)
rand_int=np.random.randint(15,20)
print(rand_int)

print("------------------------------------------------")
choice_arr = np.random.choice([1,5,10,15], size=5, replace=True, p=[0.1,0.2,0.3,0.4])
print(choice_arr)

# PERMUTATION ARRAY SYNTAX:ARR-NAME=np.random,permutation(np.arange(value))
perm_arr=np.random.permutation(np.arange(10))
print(perm_arr)
#shuffle
np.random.shuffle(perm_arr)
print(perm_arr)


[10 12 14 16 18 20 22 24 26 28]
[10. 15. 20. 25. 30.]
[  1.  10. 100.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
----------------------------------
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
----------------------------------
18
------------------------------------------------
[15  1  1 10 10]
[1 8 7 5 4 9 0 3 6 2]
[9 7 4 3 2 1 5 8 0 6]
