## **ARRAY ATTRIBUTES**

In [ ]:
import numpy as np
arr=np.array([[1+2j,3,4],[5,6,7]])
print(arr.ndim) #SHOW THE NUMBER OF DIMENSIONS
print(arr.shape) #show the row col
print(arr.dtype) #show the data type
print(arr.size) #show the number of element
print(arr.itemsize) #show the size of each element
print(arr.nbytes) #show the total number of bytes
print(arr.real) #show the real part
print(arr.imag) #show the imaginary part of array
print(arr.T) #transpose of array

2
(2, 3)
complex128
6
16
96
[[1. 3. 4.]
 [5. 6. 7.]]
[[2. 0. 0.]
 [0. 0. 0.]]
[[1.+2.j 5.+0.j]
 [3.+0.j 6.+0.j]
 [4.+0.j 7.+0.j]]


## **DATA TYPE**

In [ ]:
#SPECIFY DATA TYPE DURING CREATION
arr=np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(arr)

#convert data type
arr=arr.astype(np.int16)
print(arr)
#Ex-2
bool_arr=np.array([1,0,-1,0],dtype=np.bool_)
print(bool_arr)
'''
Common dtypes:
np.int8, np.int16, np.int32, np.int64,
np.uint8 (unsigned), np.float16, np.float32,
 np.float64, np.complex64, np.complex128,
 np.bool_, np.string_, np.object_.

 '''



[[1. 2. 3.]
 [4. 5. 6.]]
[[1 2 3]
 [4 5 6]]
[ True False  True False]


'\nCommon dtypes: \nnp.int8, np.int16, np.int32, np.int64, \nnp.uint8 (unsigned), np.float16, np.float32,\n np.float64, np.complex64, np.complex128, \n np.bool_, np.string_, np.object_.\n \n '

## **Indexing and Slicing**

In [17]:
import numpy as np
arr1d=np.arange(10)
print(arr1d)
print(arr1d[2:5])
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2d)
print(arr2d[:2,1:])
print("xxxxxxxxxxxxxxx")
#boolean index
bool_idx=(arr1d>5)
print(bool_idx)
print(arr1d[bool_idx])
print("...........................")
#we can manipulate the index via condition
print(arr2d[arr2d%2==0])
print(arr1d[(arr1d > 4) & (arr1d < 8)])

print(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,")
#indices- make a copy in in other array
indices = np.array([1,0,2])
print(arr1d[indices])
print("..................")
row_indices=np.array([0,2])
col_indices=np.array([1,0])
print(arr2d[row_indices,col_indices])
print("............................")
print(arr2d[row_indices])
print("............................")
print(arr2d[col_indices])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
xxxxxxxxxxxxxxx
[False False False False False False  True  True  True  True]
[6 7 8 9]
...........................
[2 4 6 8]
[5 6 7]
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
[1 0 2]
..................
[2 7]
............................
[[1 2 3]
 [7 8 9]]
............................
[[4 5 6]
 [1 2 3]]
