**COPYING ARRAYS**

In [5]:
import numpy as np  # Import NumPy library

print("Create a NumPy array 'a' with elements [1, 2, 3]")
a = np.array([1, 2, 3])

print("Assign array 'a' to variable 'b' (no copy, just reference)")
b = a

print("Create a view 'c' of array 'a' (shallow copy - shares data)")
c = a.view()

print("Create a deep copy 'd' of array 'a' (independent copy)")
d = a.copy()

print("Print arrays a, b, c, d")
print(a)
print(b)
print(c)
print(d)

print("Modify first element of 'b' to 100 (affects 'a' too because 'b' is a reference)")
b[0] = 100

print("Modify first element of 'c' to 200 (affects 'a' too because 'c' is a view)")
c[0] = 200

print("Modify last element of 'd' to 300 (only affects 'd' because it's a deep copy)")
d[2] = 300

print("Print all arrays after modification")
print(f"a: {a}, b: {b}, c: {c}, d: {d}")


Create a NumPy array 'a' with elements [1, 2, 3]
Assign array 'a' to variable 'b' (no copy, just reference)
Create a view 'c' of array 'a' (shallow copy - shares data)
Create a deep copy 'd' of array 'a' (independent copy)
Print arrays a, b, c, d
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
Modify first element of 'b' to 100 (affects 'a' too because 'b' is a reference)
Modify first element of 'c' to 200 (affects 'a' too because 'c' is a view)
Modify last element of 'd' to 300 (only affects 'd' because it's a deep copy)
Print all arrays after modification
a: [200   2   3], b: [200   2   3], c: [200   2   3], d: [  1   2 300]


## **SORTING**

In [9]:
import numpy as np  # Import the NumPy library

print("Create an unsorted 1D array")
unsorted_array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

print("Sort the array using np.sort() (returns a new sorted array)")
sorted_array = np.sort(unsorted_array)
print(sorted_array)

print("Sort the array in-place using .sort() (modifies the original array)")
unsorted_array.sort()
print(unsorted_array)

print("Create a 2D array for sorting along different axes")
arr2d = np.array([[0.3, 0.1, 0.2], [0.6, 0.5, 0.4]])

print("Sort the 2D array along columns (axis=0)")
print(np.sort(arr2d, axis=0))

print("Sort the 2D array along rows (axis=1)")
print(np.sort(arr2d, axis=1))

print("Use np.argsort to get the indices that would sort the array [30, 20, 10]")
idx_sorted = np.argsort(np.array([30, 20, 10]))
print(idx_sorted)

print("Create a data array for top-k extraction")
data = np.array([30, 20, 10, 50, 40])

print("Set value of k (how many top elements to extract)")
k = 3

print("Get indices of the top k largest elements")
top_k_indices = np.argsort(data)[-k:]
print(top_k_indices)

print("Use previously computed sorted indices to reorder another array")
print(data[idx_sorted])  # Note: `idx_sorted` came from a different array

print("Get top k values using the indices")
top_k_values = data[top_k_indices]
print(top_k_values)


Create an unsorted 1D array
Sort the array using np.sort() (returns a new sorted array)
[1 1 2 3 3 4 5 5 5 6 9]
Sort the array in-place using .sort() (modifies the original array)
[1 1 2 3 3 4 5 5 5 6 9]
Create a 2D array for sorting along different axes
Sort the 2D array along columns (axis=0)
[[0.3 0.1 0.2]
 [0.6 0.5 0.4]]
Sort the 2D array along rows (axis=1)
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
Use np.argsort to get the indices that would sort the array [30, 20, 10]
[2 1 0]
Create a data array for top-k extraction
Set value of k (how many top elements to extract)
Get indices of the top k largest elements
[0 4 3]
Use previously computed sorted indices to reorder another array
[10 20 30]
Get top k values using the indices
[30 40 50]


# **LENEAR ALGEBRA**

In [11]:
import numpy as np  # Import NumPy library

print("Create a 2x2 matrix A")
A = np.array([[1., 2.], [3., 4.]])

print("Create a 1D vector v")
v = np.array([1., 0.5])

print("Compute the inverse of matrix A")
A_inv = np.linalg.inv(A)
print(A_inv)

print("Compute the determinant of matrix A")
det_A = np.linalg.det(A)
print(det_A)

print("Compute the eigenvalues and eigenvectors of matrix A")
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

print("Create a vector b for the linear equation Ax = b")
b_vec = np.array([5., 7.])

print("Solve the linear system Ax = b")
x_sol = np.linalg.solve(A, b_vec)
print(x_sol)

print("Perform Singular Value Decomposition (SVD) on matrix A")
U, S, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Singular values:", S)
print("V^T matrix:\n", Vt)

print("Compute the L2 norm (default) of vector v")
print(np.linalg.norm(v))

print("Compute the L1 norm of vector v")
print(np.linalg.norm(v, ord=1))

print("Compute the infinity norm of vector v")
print(np.linalg.norm(v, ord=np.inf))

print("Compute the L2 norm (Euclidean) of vector v")
print(np.linalg.norm(v, ord=2))

print("Compute the Frobenius norm (default) of matrix A")
print(np.linalg.norm(A))

print("Compute the matrix 1-norm (maximum column sum) of matrix A")
print(np.linalg.norm(A, ord=1))

print("Compute the matrix infinity norm (maximum row sum) of matrix A")
print(np.linalg.norm(A, ord=np.inf))

print("Compute the matrix 2-norm (spectral norm) of matrix A")
print(np.linalg.norm(A, ord=2))

print("Compute the trace of matrix A (sum of diagonal elements)")
print(np.trace(A))


[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[-3.  4.]
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[5.4649857  0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
1.118033988749895
1.5
1.0
1.118033988749895
5.477225575051661
6.0
7.0
5.464985704219043
5.0
