# **UNIVERSAL FUNCTION**

In [4]:
import numpy as np  # Import the NumPy library

print("Create a 1D NumPy array 'a' with elements [1, 2, 3]")
a = np.array([1, 2, 3])

print("Create another 1D NumPy array 'b' with elements [4, 5, 6]")
b = np.array([4, 5, 6])

print("Element-wise addition of 'a' and 'b'")
print(a + b)

print("Element-wise addition using np.add()")
print(np.add(a, b))

print("Multiply each element in 'a' by 5")
print(a * 5)

print("Element-wise division of 'a' by 'b'")
print(a / b)

print("Square each element in 'a'")
print(a ** 2)

print("Cube each element in 'a'")
print(a ** 3)

print("Exponential (e^x) of each element in 'a'")
print(np.exp(a))

print("Natural logarithm (ln) of each element in 'a'")
print(np.log(a))

print("Square root of each element in 'a'")
print(np.sqrt(a))

print("Sine of each element in 'a' (in radians)")
print(np.sin(a))

print("Check if elements of 'a' are less than 2")
print(a < 2)

print("Element-wise comparison: a[i] > b[i]")
print(np.greater(a, b))

print("Create a 3x3 matrix 'm1'")
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Create another 3x3 matrix 'm2'")
m2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

print("Element-wise addition of 'm1' and 'm2'")
print(m1 + m2)

print("Element-wise multiplication (Hadamard product)")
print(m1 * m2)

print("Matrix multiplication (dot product) of 'm1' and 'm2'")
print(np.dot(m1, m2))

print("Find the maximum element in 'm1'")
print(m1.max())

print("Calculate the sum of all elements in 'm1'")
print(m1.sum())

print("Calculate the mean (average) of all elements in 'm1'")
print(m1.mean())

print("Calculate the standard deviation of all elements in 'm1'")
print(m1.std())

print("Calculate the variance of all elements in 'm1'")
print(m1.var())

print("Maximum value along each column of 'm1'")
print(m1.max(axis=0))

print("Print a separator line")
print(".........")

print("Find the minimum element in 'm1'")
print(m1.min())

print("Cumulative sum of the flattened 'm1' array")
print(m1.cumsum())

print("Cumulative product of the flattened 'm1' array")
print(m1.cumprod())

print("Print another separator line")
print("..................................................")

print("Transpose of matrix 'm1'")
print(m1.T)

print("Matrix multiplication using '@' operator")
print(m1 @ m2)

print("Dot product of 1D arrays 'a' and 'b'")
print(a.dot(b))

print("Create a 2x3 matrix 'arr'")
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum of all elements in 'arr' using np.sum()")
print(np.sum(arr))

print("Sum of all elements in 'arr' using method syntax")
print(arr.sum())

print("Sum along columns (axis=0)")
print(np.sum(arr, axis=0))

print("Sum along rows (axis=1)")
print(np.sum(arr, axis=1))

print("Mean of all elements in 'arr'")
print(np.mean(arr))

print("Mean of each column")
print(np.mean(arr, axis=0))

print("Mean of each row")
print(np.mean(arr, axis=1))

print("Standard deviation of all elements in 'arr'")
print(np.std(arr))

print("Standard deviation for each column")
print(np.std(arr, axis=0))

print("Standard deviation for each row")
print(np.std(arr, axis=1))

print("Variance of all elements")
print(np.var(arr))

print("Variance for each column")
print(np.var(arr, axis=0))

print("Variance for each row")
print(np.var(arr, axis=1))

print("Minimum value in the array (two equivalent ways)")
print(np.min(arr), arr.min())

print("Minimum value for each column")
print(np.min(arr, axis=0), arr.min(axis=0))

print("Minimum value for each row")
print(np.min(arr, axis=1), arr.min(axis=1))

print("Maximum value in the array (two equivalent ways)")
print(np.max(arr), arr.max())

print("Maximum value for each column")
print(np.max(arr, axis=0), arr.max(axis=0))

print("Maximum value for each row")
print(np.max(arr, axis=1), arr.max(axis=1))

print("Index of the minimum value for each column")
print(np.argmin(arr, axis=0))

print("Index of the minimum value for each row")
print(np.argmin(arr, axis=1))

print("Index of the maximum value for each column")
print(np.argmax(arr, axis=0))

print("Index of the maximum value for each row")
print(np.argmax(arr, axis=1))

print("Cumulative sum of the flattened array")
print(np.cumsum(arr))

print("Cumulative product of the flattened array")
print(np.cumprod(arr))

print("Sort each row of 'arr'")
print(np.sort(arr))

print("Sort each column of 'arr'")
print(np.sort(arr, axis=0))

print("Sort each row of 'arr'")
print(np.sort(arr, axis=1))

print("Product of all elements in 'arr'")
print(np.prod(arr))

print("Product of elements in each column")
print(np.prod(arr, axis=0))

print("Product of elements in each row")
print(np.prod(arr, axis=1))

print("Check if all elements are non-zero")
print(np.all(arr))

print("Check if any element is non-zero")
print(np.any(arr))


Create a 1D NumPy array 'a' with elements [1, 2, 3]
Create another 1D NumPy array 'b' with elements [4, 5, 6]
Element-wise addition of 'a' and 'b'
[5 7 9]
Element-wise addition using np.add()
[5 7 9]
Multiply each element in 'a' by 5
[ 5 10 15]
Element-wise division of 'a' by 'b'
[0.25 0.4  0.5 ]
Square each element in 'a'
[1 4 9]
Cube each element in 'a'
[ 1  8 27]
Exponential (e^x) of each element in 'a'
[ 2.71828183  7.3890561  20.08553692]
Natural logarithm (ln) of each element in 'a'
[0.         0.69314718 1.09861229]
Square root of each element in 'a'
[1.         1.41421356 1.73205081]
Sine of each element in 'a' (in radians)
[0.84147098 0.90929743 0.14112001]
Check if elements of 'a' are less than 2
[ True False False]
Element-wise comparison: a[i] > b[i]
[False False False]
Create a 3x3 matrix 'm1'
Create another 3x3 matrix 'm2'
Element-wise addition of 'm1' and 'm2'
[[11 13 15]
 [17 19 21]
 [23 25 27]]
Element-wise multiplication (Hadamard product)
[[ 10  22  36]
 [ 52  70  90

## **BROADCASTING**

In [13]:
import numpy as np  # Import NumPy library

print("Create a 2x3 array with values from 0 to 5 using arange and reshape")
arr = np.arange(6).reshape((2, 3))
print(arr)

print("Calculate the mean of each row (axis=1)")
row_mean = arr.mean(axis=1)
print(row_mean)

print("Subtract row-wise mean from each element (broadcasted subtraction)")
print(arr - row_mean[:, np.newaxis])  # Subtract each row's mean from the row

print("Add scalar value 100 to each element in the array")
scaler_add = arr + 100
print(scaler_add)


Create a 2x3 array with values from 0 to 5 using arange and reshape
[[0 1 2]
 [3 4 5]]
Calculate the mean of each row (axis=1)
[1. 4.]
Subtract row-wise mean from each element (broadcasted subtraction)
[[-1.  0.  1.]
 [-1.  0.  1.]]
Add scalar value 100 to each element in the array
[[100 101 102]
 [103 104 105]]


## **Shape Manipulation**

In [19]:
import numpy as np  # Import NumPy library

print("Create a 1D array with values from 0 to 11")
arr = np.arange(12)

print("Reshape the array into shape (3, 4)")
reshape_arr = arr.reshape(3, 4)

print("Reshape the array using -1 to automatically determine the second dimension")
reshape_arr_neg_one = arr.reshape(2, -1)

print("Flatten the reshaped array into a 1D array using flatten()")
flattened_arr = reshape_arr.flatten()

print("Flatten the reshaped array using ravel() (returns a view if possible)")
ravelled_arr = reshape_arr.ravel()

print("Transpose the reshaped array")
print(reshape_arr.T)

print("Add a new axis to convert the 1D array to a column vector (shape becomes (12,1))")
expnded_dim_col = arr[:, np.newaxis]
print(expnded_dim_col)

print("Add a new axis to convert the 1D array to a row vector (shape becomes (1,12))")
expnded_dim_row = arr[np.newaxis, :]
print(expnded_dim_row)

print("Create array 'a' as a 2x2 matrix")
a = np.array([[1, 2], [3, 4]])

print("Create array 'b' as a 1x2 matrix")
b = np.array([[5, 6]])

print("Create array 'c' as a 2x1 matrix")
c = np.array([[5], [6]])

print("Stack arrays 'a' and 'b' vertically (vstack)")
print(np.vstack((a, b)))

print("Stack arrays 'a' and 'c' horizontally (hstack)")
print(np.hstack((a, c)))

print("Concatenate arrays 'a' and 'b' along axis 0 (same as vstack)")
print(np.concatenate((a, b), axis=0))

print("Concatenate arrays 'a' and 'c' along axis 1 (same as hstack)")
print(np.concatenate((a, c), axis=1))

print("Create a 3x3 array with values 0 to 8 to demonstrate splitting")
arr_spilt = np.arange(9).reshape(3, 3)
print(arr_spilt)

print("Split the array into 3 equal sub-arrays (default axis=0)")
print(np.split(arr_spilt, 3))

print("Split the array into 3 parts along axis=0 (rows)")
print(np.split(arr_spilt, 3, axis=0))

print("Split the array into 3 parts along axis=1 (columns)")
print(np.split(arr_spilt, 3, axis=1))

print("Split the array horizontally into 3 columns (hsplit)")
print(np.hsplit(arr_spilt, 3))

print("Split the array vertically into 3 rows (vsplit)")
print(np.vsplit(arr_spilt, 3))


Create a 1D array with values from 0 to 11
Reshape the array into shape (3, 4)
Reshape the array using -1 to automatically determine the second dimension
Flatten the reshaped array into a 1D array using flatten()
Flatten the reshaped array using ravel() (returns a view if possible)
Transpose the reshaped array
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Add a new axis to convert the 1D array to a column vector (shape becomes (12,1))
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
Add a new axis to convert the 1D array to a row vector (shape becomes (1,12))
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
Create array 'a' as a 2x2 matrix
Create array 'b' as a 1x2 matrix
Create array 'c' as a 2x1 matrix
Stack arrays 'a' and 'b' vertically (vstack)
[[1 2]
 [3 4]
 [5 6]]
Stack arrays 'a' and 'c' horizontally (hstack)
[[1 2 5]
 [3 4 6]]
Concatenate arrays 'a' and 'b' along axis 0 (same as vstack)
[[1 2]
 [3 4]
 [5 6]]
Concatenate arrays 'a' and 'c' along axis 1 (same as